### PR TITLE
Support changing AA settings on a context.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/core-graphics-rs/56)

### CODE REVIEW

**Comment by glennw** [comment]
What's the appropriate fix for the travis failures on types unrelated to this PR?

```
error: private type in public interface (error E0446), #[deny(private_in_public)] on by default
```

**Comment by emilio** [comment]
@glennw: You need to make the `struct __CGFoo` types public. Ideally, make them also an enum without variants so they can't be instantiated e.g.: `pub enum __CGContext {}`.

r=me with that, I've read the [`CGContext` documentation](https://developer.apple.com/library/ios/documentation/GraphicsImaging/Reference/CGContext/index.html), and this seems sound to me.

**Comment by glennw** [comment]
Rebased after @nox kindly fixed up the travis errors.

**Pull request merged**
