### PR TITLE
Add support for CGEventSetType

### PR DESCRIPTION
**Pull request by msanders**
This change is [Reviewable](https://reviewable.io/reviews/servo/core-graphics-rs/72)

### CODE REVIEW

**Comment by KiChjang** [comment]
Huh, looking at Travis CI's logs, I see that it's trying to rebuild #69 again and again... @jdm is there a way to fix this?

**Comment by jdm** [comment]
@edunham @larsbergstrom Do either of you have any suggestions for how to figure out what homu is doing here? Homu hasn't been able to merge any PRs in this repository for days, despite the TravisCI integration always reporting successful builds prior to telling homu to merge (which should skip any need to rebuild).

**Comment by jdm** [comment]
@metajack See previous comment.

**Comment by metajack** [comment]
I'm betting that the Travis CI hook to Homu isn't set up.

**Comment by jdm** [comment]
It certainly used to work, then it became finnicky but worked if homu decided to skip tests because the Travis results were valid. Then it stopped working altogether.

**Comment by metajack** [comment]
And this epic now has a happy ending!

**Pull request merged**
