### PR TITLE
Allow applying multiple bitmask flags to events

### PR DESCRIPTION
**Pull request by msanders**
This change is [Reviewable](https://reviewable.io/reviews/servo/core-graphics-rs/74)

### CODE REVIEW

**Comment by jdm** [comment]
I can't find any record of a CGEventFlagMask type, and the [docs](https://developer.apple.com/reference/coregraphics/1455642-cgeventgetflags?language=objc) show the CGEventFlags type in use. What's the reasoning behind this change?

**Comment by msanders** [comment]
It's necessary to pass in multiple flags, e.g. `event.set_flags(CGEventFlags::AlphaShift | CGEventFlags::Control)`. Alternatively, we could pass in the flags as an array or use the [bitflags](https://doc.rust-lang.org/bitflags/bitflags/macro.bitflags.html) crate — I can change it do that instead if it would be preferred.

**Comment by jdm** [comment]
Oh, I see. Changing CGEventFlags to use the bitflags crate would be clearer, in that case.

**Comment by msanders** [comment]
Cool, fixed.

**Pull request merged**
