### PR TITLE
Upgrade to libc 0.2

### PR DESCRIPTION
**Pull request by mbrubeck**
[Review on Reviewable](https://reviewable.io/reviews/servo/core-graphics-rs/45)

### CODE REVIEW

**Comment by metajack** [comment]
Also needs a rebase.

**Comment by mbrubeck** [comment]
Depends on servo/core-foundation-rs#71.

**Comment by metajack** [comment]
@bors-servo r+


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/core-graphics-rs/45)

**Comment by jdm** [comment]
core-foundation hasn't been published yet.

**Comment by jdm** [comment]
Interestingly, I tried to do so and discovered that core-foundation-sys has been claimed on crates.io but doesn't show in search results.

**Comment by metajack** [comment]
I noticed these as well. I think that's a search bug, because the pacakge definitely exists there.

**Comment by metajack** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
I'm a little confused, what's going on here? The [`core-foundation-sys` crate exists](https://crates.io/crates/core-foundation-sys) and [`core-foundation`](https://crates.io/crates/core-foundation) doesn't have an 0.2.0 published?

**Comment by metajack** [comment]
@alexcrichton Go to crates.io and search for "core-foundation" and notice that "core-foundation-sys" does not show up. But you can search for "core-foundation-sys" and it does show up. That seems like a crates.io search bug.

**Comment by alexcrichton** [comment]
Ah yeah the search on the web I wouldn't describe as fantastic quality :)

**Pull request merged**
